version: '2'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile 
    ports:
      - '80:8087'

  flaskapp:
    build:
      context: .
      dockerfile: flask.Dockerfile
    volumes:
      - .:/root/Sunpath/
    ports:
      - 8050:8050
    stdin_open: true
    tty: true