#Static Variables for dashboard
SELLERS = {
     'ALLIANCE WS': 'ALLIANCE WS -SF',
     'AUTO PREMIER PROTECTION': 'AUTO PREMIER PROTECTION -SF',
     'AUTO PROTECTION PLUS': 'AUTO PROTECTION PLUS -SF',
     'AUTOMOTIVE SERVICES CENTER': 'AUTOMOTIVE SERVICES CENTER -SF',
     'DIRECT SERVICE DIVISION': 'DIRECT SERVICE DIVISION -SF',
     'GLOBAL AUTOMOTIVE SERVICES': 'GLOBAL AUTOMOTIVE SERVICES -SF',
     'HiTEK AUTO PROTECTION': 'HiTEK AUTO PROTECTION -SF',
     'KEYSTONE SALES LLC': 'KEYSTONE SALES LLC -SF',
     'MOTOR VEHICLE PROTECTION SERVICES': 'MOTOR VEHICLE PROTECTION SERVICES -SF',
     'NAPC': 'NAPC - SIMPLICITY',
     'NATIONAL AUTO PROTECTION CORP': 'NATIONAL AUTO PROTECTION CORP -SF',
     'NATIONWIDE AUTO GUARD': 'NATIONWIDE AUTO GUARD -SF',
     'NATIONWIDE VEHICLE ASSURANCE CORP': 'NATIONWIDE VEHICLE ASSURANCE CORP -SF',
     'PEOPLES CHOICE AUTO PROTECTION SERVICES': 'PEOPLES CHOICE AUTO PROTECTION SERVICES -SF',
     'PROTECH VEHICLE SERVICES': 'PROTECH VEHICLE SERVICES -SF',
     'SIMPLY AUTO PROTECTION': 'SIMPLY AUTO PROTECTION -SF',
     'SPANISH SERVICE CENTER': 'SPANISH SERVICE CENTER -SF',
     'ULTIMATE AUTO PROTECTION': 'ULTIMATE AUTO PROTECTION -SF',
     'VEHICLE PROTECTION SPECIALISTS': 'VEHICLE PROTECTION SPECIALISTS -SF',
     'VEHICLE PROTECTION USA': 'VEHICLE PROTECTION USA -SF'
}

TXCODES = {
     'ALLIANCE WS -SF': ('AWS7773', 'AWS'),
     'AUTO PREMIER PROTECTION -SF': ('APP3316', 'APPH'),
     'AUTO PROTECTION PLUS -SF': ('APP7951', 'APP'),
     'AUTOMOTIVE SERVICES CENTER -SF': ('ASC4068', 'ASC'),
     'DIRECT SERVICE DIVISION -SF': ('DSD3712', 'DSD'),
     'GLOBAL AUTOMOTIVE SERVICES -SF': ('GAS0373', 'GAS'),
     'HiTEK AUTO PROTECTION -SF': ('HTA4333', 'HTA'),
     'KEYSTONE SALES LLC -SF': ('KEY9786', 'KEY'),
     'MOTOR VEHICLE PROTECTION SERVICES -SF': ('MVPS420', 'MVPS'),
     'NAPC - SIMPLICITY': ('NAP71145','NAPS'),
     'NATIONAL AUTO PROTECTION CORP -SF': ('NAP7114', 'NAP'),
     'NATIONWIDE AUTO GUARD -SF': ('NAG5935', 'NAG'),
     'NATIONWIDE VEHICLE ASSURANCE CORP -SF': ('NVA9952', 'NVA'),
     'PEOPLES CHOICE AUTO PROTECTION SERVICES -SF': ('PCA0550', 'PCA'),
     'PROTECH VEHICLE SERVICES -SF': ('PRO0808', 'PRO'),
     'SIMPLY AUTO PROTECTION -SF': ('SAP6890', 'SAP'),
     'SPANISH SERVICE CENTER -SF': ('SSC0609', 'SSC'),
     'ULTIMATE AUTO PROTECTION -SF': ('UAP3570', 'UAP'),
     'VEHICLE PROTECTION SPECIALISTS -SF': ('VPS0804', 'VPS'),
     'VEHICLE PROTECTION USA -SF': ('VPU5716', 'VPU')
}

SHORTCODES = {
    'APP': 'AUTO PROTECTION PLUS',
    'APPH': 'AUTO PREMIER PROTECTION',
    'ASC': 'AUTOMOTIVE SERVICES CENTER',
    'AWS': 'ALLIANCE WS',
    'DSD': 'DIRECT SERVICE DIVISION',
    'GAS': 'GLOBAL AUTOMOTIVE SERVICES',
    'HTA': 'HiTEK AUTO PROTECTION',
    'KEY': 'KEYSTONE SALES LLC',
    'MVPS': 'MOTOR VEHICLE PROTECTION SERVICES',
    'NAG': 'NATIONWIDE AUTO GUARD',
    'NAP': 'NATIONAL AUTO PROTECTION CORP',
    'NAPS': 'NAPC',
    'NVA': 'NATIONWIDE VEHICLE ASSURANCE CORP',
    'PCA': 'PEOPLES CHOICE AUTO PROTECTION SERVICES',
    'PRO': 'PROTECH VEHICLE SERVICES',
    'SAP': 'SIMPLY AUTO PROTECTION',
    'SSC': 'SPANISH SERVICE CENTER',
    'UAP': 'ULTIMATE AUTO PROTECTION',
    'VPS': 'VEHICLE PROTECTION SPECIALISTS',
    'VPU': 'VEHICLE PROTECTION USA',
    'SPF': 'SUNPATH FUNDING',
    'SP_INS': 'SUNPATH INS',
    'SP_ADM': 'SUNPATH ADM',
    'PAYLINK':'PAYLINK',
    None : 'None'
}
FUNDERS = {
    'SUNPATH (SPF)': 0,
    'SIMPLICITY': 1
}
